<?php


 /**
  * Ciudad Value Object.
  * This class is value object representing database table tblciudad
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */




class Ciudad {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    var $idCiudad;
    var $nombre_ciudad;
    var $secdepartamento;
    var $latitud;
    var $longitud;
    var $secbarrio;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    function Ciudad () {

    }

    /* function Ciudad ($idCiudadIn) {

          $this->idCiudad = $idCiudadIn;

    } */


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    function getIdCiudad() {
          return $this->idCiudad;
    }
    function setIdCiudad($idCiudadIn) {
          $this->idCiudad = $idCiudadIn;
    }

    function getNombre_ciudad() {
          return $this->nombre_ciudad;
    }
    function setNombre_ciudad($nombre_ciudadIn) {
          $this->nombre_ciudad = $nombre_ciudadIn;
    }

    function getSecdepartamento() {
          return $this->secdepartamento;
    }
    function setSecdepartamento($secdepartamentoIn) {
          $this->secdepartamento = $secdepartamentoIn;
    }

    function getLatitud() {
          return $this->latitud;
    }
    function setLatitud($latitudIn) {
          $this->latitud = $latitudIn;
    }

    function getLongitud() {
          return $this->longitud;
    }
    function setLongitud($longitudIn) {
          $this->longitud = $longitudIn;
    }

    function getSecbarrio() {
          return $this->secbarrio;
    }
    function setSecbarrio($secbarrioIn) {
          $this->secbarrio = $secbarrioIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    function setAll($idCiudadIn,
          $nombre_ciudadIn,
          $secdepartamentoIn,
          $latitudIn,
          $longitudIn,
          $secbarrioIn) {
          $this->idCiudad = $idCiudadIn;
          $this->nombre_ciudad = $nombre_ciudadIn;
          $this->secdepartamento = $secdepartamentoIn;
          $this->latitud = $latitudIn;
          $this->longitud = $longitudIn;
          $this->secbarrio = $secbarrioIn;
    }


    /** 
     * hasEqualMapping-method will compare two Ciudad instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    function hasEqualMapping($valueObject) {

          if ($valueObject->getIdCiudad() != $this->idCiudad) {
                    return(false);
          }
          if ($valueObject->getNombre_ciudad() != $this->nombre_ciudad) {
                    return(false);
          }
          if ($valueObject->getSecdepartamento() != $this->secdepartamento) {
                    return(false);
          }
          if ($valueObject->getLatitud() != $this->latitud) {
                    return(false);
          }
          if ($valueObject->getLongitud() != $this->longitud) {
                    return(false);
          }
          if ($valueObject->getSecbarrio() != $this->secbarrio) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    function toString() {
        $out = $this->getDaogenVersion();
        $out = $out."\nclass Ciudad, mapping to table tblciudad\n";
        $out = $out."Persistent attributes: \n"; 
        $out = $out."idCiudad = ".$this->idCiudad."\n"; 
        $out = $out."nombre_ciudad = ".$this->nombre_ciudad."\n"; 
        $out = $out."secdepartamento = ".$this->secdepartamento."\n"; 
        $out = $out."latitud = ".$this->latitud."\n"; 
        $out = $out."longitud = ".$this->longitud."\n"; 
        $out = $out."secbarrio = ".$this->secbarrio."\n"; 
        return $out;
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    function clonar() {
        $cloned = new Ciudad();

        $cloned->setIdCiudad($this->idCiudad); 
        $cloned->setNombre_ciudad($this->nombre_ciudad); 
        $cloned->setSecdepartamento($this->secdepartamento); 
        $cloned->setLatitud($this->latitud); 
        $cloned->setLongitud($this->longitud); 
        $cloned->setSecbarrio($this->secbarrio); 

        return $cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    function getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

?>